name: Deploy R

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: R
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./R/context
          file: Dockerfile
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:v4.0.3
          
          
